### ISSUE TITLE
Agregar Instrucciones de configuración inicial y corrida al README

### ISSUE THREAD

**Issue by redcpp** [AngelCarballoCremades/CENACE-Scraper-Dashboard#1]
Tener una sección de Setup y Run en el README con código para copiar y pegar sería bueno para así distinguir que archivos son los que se tienen que correr directamente y en que orden.

La sección de Setup pudiera ir explicando paso a paso la instalación de requisitos y dependencias necesarias. Ejemplo:

1. Pre-requisitos: Instalar PostgresSQL, Python3, Virtualenv, etc.
2. ./venv/bin/activate # activar el ambiente
3. pip install -r requirements.txt # Instalar dependencias
4. python dashboard.py # Correr el dashboard
5. ...
6. Ir a https://localhost:8000

**Comment by AngelCarballoCremades** [comment]
Agregaré  a lo largo de esta y la siguiente semana las instrucciones para un setup adecuado.

Es mi primer proyecto y espero que te sea útil. 
Falta que comente más el código, pero poco a poco lo iré mejorando.
Mi idea es hacerlo disponible en una página web para que sea más fácil de accesar.
Siéntete libre de hacer cualquier comentario o propuesta de modificación!

**Comment by AngelCarballoCremades** [comment]
Ya agregué la sección.
También está hosteado todo el proyecto en heroku, este es el link: https://mexico-energy-dashboard.herokuapp.com/
Gracias por el comentario, quedo al pendiente de cualquier otra duda o propuesta de modificación.
:)
